export const tags = [
  { code: "dz1", name: "Dział 1 - Pomiary Strategiczne", index: 1 },
  { code: "elemBaz", name: "Elementy Bazowe", index: 2 },
  { code: "metWyznUkl", name: "Metody Wyznaczania układów Współrzędnych", index: 3 },
  { code: "techPom", name: "Techniki pomiarowe współrzędnościowe", index: 2 },
  { code: "maszyny", name: "Podstawowe konstrukcje maszyn współrzędnościowych", index: 3 },
  { code: "dz2", name: "Dział 2 - Układy pomiarowe i Sondy pomiarowe", index: 1 },
  { code: "uklPom", name: "Układy pomiarowe", index: 2 },
  { code: "glowice", name: "Głowice (sondy pomiarowe)", index: 2 },
  { code: "dz3", name: "Dział 3 - Odchyłki Geometryczne ISO 1101, Systemy pomiarowe z elementami SKJ", index: 1 },
  { code: "podzTol", name: "Podział Tolerancji", index: 2 },
  { code: "metody", name: "Metody obliczania elementów odniesienia", index: 2 },
  { code: "dz4", name: "Fotogrametria i Tomografia", index: 1 },
  { code: "foto", name: "Fotogrametria", index: 2 },
  { code: "tom", name: "Tomografia komputerowa", index: 2 },
  { code: "zagadnieniaSem1", name: "Zagadnienia stare", index: 1 },
  { code: "s1p1", name: "1-10", index: 2 },
  { code: "s1p2", name: "11-21", index: 2 },
  { code: "s1p3", name: "22-23", index: 2 },
  { code: "zagadnieniaSem2", name: "Zagadnienia nowe", index: 1 },
  { code: "s2p1", name: "1-8", index: 2 },
  { code: "s2p2", name: "9-15", index: 2 },
];

// { code: "", name: "" },
